version: 2

build:
  os: ubuntu-22.04

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# We want to build a conda environment from our environment.yml
conda:
  environment: docs/environment.yml
