import pandas as pd
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

class PyMOLVisualizer:
    """
    Generates PyMOL visualization scripts (.pml) from MM/GBSA decomposition results.
    """
    
    def __init__(self, output_dir):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def generate_script(self, decomposition_csv, pdb_file, output_filename="view_binding.pml", 
                       energy_threshold=-0.5, ligand_resname="LIG", distance_cutoff=5.0):
        """
        Generate a PyMOL script to visualize binding hotspots.
        
        Args:
            decomposition_csv (str or Path): Path to the final decomposition CSV.
            pdb_file (str or Path): Path to the structure file (PDB) to load.
            output_filename (str): Name of the output .pml file.
            energy_threshold (float): Energy cutoff (kcal/mol) to consider a residue a hotspot.
                                      Default is -0.5 (visualization includes anything stronger than this).
            ligand_resname (str): Residue name of the ligand for selection.
        """
        try:
            csv_path = Path(decomposition_csv)
            if not csv_path.exists():
                logger.warning(f"Decomposition CSV not found at {csv_path}. Skipping PyMOL script generation.")
                return

            df = pd.read_csv(csv_path)
            
            # Filter for significant residues (Standard naming: total_mean or total)
            # Handle both Full and Fast mode column names if they differ slighty
            # Full: 'total', Fast: 'total_mean'
            col_name = 'total' if 'total' in df.columns else 'total_mean'
            
            if col_name not in df.columns:
                 logger.warning(f"Could not find total energy column ('total' or 'total_mean') in {csv_path}")
                 return
                 
            # Filter hotspots (Energy < threshold, i.e., more negative is stronger)
            hotspots = df[df[col_name] < energy_threshold].copy()
            
            # Sort by contribution (strongest first)
            hotspots = hotspots.sort_values(by=col_name, ascending=True)
            
            # Prepare PyMOL commands
            pml_content = []
            pml_content.append(f"# PyMOL Visualization Script for MM/GBSA Results")
            pml_content.append(f"# Generated by Athena/Antigravity")
            pml_content.append(f"")
            
            # Load Structure
            # We assume the PDB file is relative to the results dir or absolute.
            pdb_abs_path = Path(pdb_file).resolve()
            pml_content.append(f"load {pdb_abs_path}, complex")
            pml_content.append("hide everything")
            pml_content.append("bg_color white")
            pml_content.append("")
            
            # Styling Settings (Thinner/Cleaner)
            pml_content.append("# Styling Settings")
            pml_content.append("set cartoon_oval_length, 0.7")
            pml_content.append("set cartoon_rect_length, 0.7")
            pml_content.append("set stick_radius, 0.15")
            pml_content.append("set dash_gap, 0.5")
            pml_content.append("set dash_length, 0.5")
            pml_content.append("set dash_radius, 0.05")
            pml_content.append("")
            
            # Show Cartoon for Protein
            pml_content.append("# Protein Representation")
            pml_content.append("show cartoon, complex")
            pml_content.append("color white, complex")
            pml_content.append("set cartoon_transparency, 0.4")
            pml_content.append("")
            
            # Show Ligand
            pml_content.append("# Ligand Representation")
            pml_content.append(f"select ligand, resn {ligand_resname}")
            pml_content.append("show sticks, ligand")
            pml_content.append("color green, ligand")
            pml_content.append("util.cnc ligand")
            pml_content.append("")
            
            # Distance Selection
            pml_content.append(f"# Select Residues Near Ligand ({distance_cutoff} A)")
            pml_content.append(f"select near_ligand, byres complex within {distance_cutoff} of ligand")
            pml_content.append("")

            # Highlight Hotspots
            pml_content.append(f"# Hotspots (Energy < {energy_threshold} kcal/mol) within {distance_cutoff}A")
            
            for idx, row in hotspots.iterrows():
                res_id_str = str(row.get('residue', row.get('residue_id', '')))
                
                # Parse "GLU_11_A" -> Name=GLU, Num=11, Chain=A
                parts = res_id_str.split('_')
                if len(parts) >= 3:
                     r_name, r_num, r_chain = parts[0], parts[1], parts[2]
                     sel_name = f"res_{r_num}_{r_chain}"
                     # Selection: Specific residue AND within 5A of ligand
                     selection = f"resi {r_num} and chain {r_chain} and complex and near_ligand"
                else:
                    continue
                
                energy = row[col_name]
                
                # Define selection for this residue
                pml_content.append(f"select {sel_name}, {selection}")
                # Only show/color if the selection is not empty (PyMOL handles empty typically fine)
                pml_content.append(f"show sticks, {sel_name}")
                
                # Color gradient based on energy
                if energy < -5.0:
                    color = "blue"
                elif energy < -3.0:
                    color = "marine"
                elif energy < -1.5:
                    color = "cyan"
                else:
                    color = "lightteal"
                
                pml_content.append(f"color {color}, {sel_name}")
                # Label only CA atom
                pml_content.append(f"label {sel_name} and name CA, '{r_name}{r_num}: {energy:.2f}'")

            pml_content.append("")
            pml_content.append("# Final View")
            pml_content.append("deselect")
            pml_content.append("zoom ligand, 8")
            pml_content.append("set label_size, 18")
            pml_content.append("set label_position, (0,0,10)")
            pml_content.append("set label_color, black")
            pml_content.append("ray")
            
            # Write file
            output_path = self.output_dir / output_filename
            with open(output_path, 'w') as f:
                f.write("\n".join(pml_content))
                
            logger.info(f"PyMOL script generated: {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Failed to generate PyMOL script: {e}")
            return None
