package:
  name: opengbsa
  version: "0.0.2"

source:
  path: ..

build:
  noarch: python
  script: pip install . --no-deps --ignore-installed

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8,<3.13
    - openmm >=8.0.0,<8.3
    - mdtraj >=1.9.0
    - openff-toolkit >=0.14.0
    - openmmforcefields
    - prolif >=2.0.0
    - rdkit
    - mdanalysis
    - numpy >=1.21.0,<2.0.0
    - scipy >=1.7.0
    - pandas >=1.3.0
    - h5py >=3.7.0
    - matplotlib >=3.5.0
    - seaborn >=0.11.0
    - pyyaml >=6.0
    - pathlib2 >=2.3.0

about:
  home: https://github.com/Bio-Otto/opengbsa
  license: MIT
  license_file: LICENSE
  summary: "OpenGBSA - A comprehensive MM/GBSA analysis package with advanced features"
  description: |
    OpenGBSA is a comprehensive MM/GBSA analysis package with advanced features including entropy analysis, per-residue decomposition, and YAML-based configuration.

extra:
  recipe-maintainers:
    - bio-otto 